### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by aurorainbowrealis** [scotchkorean27/showdownaiclient#1]
I simply download and type `node app.js` and it returns the following error for Both 6.10 and 7.7 versions of nodejs

```
TypeError: Exported property `Formats`from `./config/formats.js` must be an array.
    at Tools.module.exports.Tools.includeFormats (C:\Users\Victor\Desktop\Pokemon Competition\showdownaiclient-master\zarel\tools.js:1143:44)
    at Tools.module.exports.Tools.includeData (C:\Users\Victor\Desktop\Pokemon Competition\showdownaiclient-master\zarel\tools.js:1078:9)
    at Object.<anonymous> (C:\Users\Victor\Desktop\Pokemon Competition\showdownaiclient-master\app.js:3:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7) 
```

**Comment by scotchkorean27** [comment]
Thanks for the heads up!  Will look into this.

**Comment by scotchkorean27** [comment]
Can you try and see if it works now?

**Comment by aurorainbowrealis** [comment]
Thanks I've been able to run it, I will look into it and let u know if there is any issues. Thanks :D
